# hardware decoding - AMD
hwdec=vaapi
hwdec-codecs=all

# native wayland output
vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
ao=pulse

# scaling
correct-downscaling=no
scale=mitchell
dscale=mitchell
cscale=mitchell

# HDR tone mapping
tone-mapping=bt.2390
hdr-peak-decay-rate=200
hdr-compute-peak=yes
target-colorspace-hint=no

# smoothness
# video-sync=display-resample
interpolation=yes

# cache for smoother local file playback
cache=yes
demuxer-max-bytes=400MiB
demuxer-max-back-bytes=100MiB
demuxer-readahead-secs=30
cache-pause=no

# subtitles
sub-auto=fuzzy
sub-font-size=38

# screenshot format
screenshot-format=png
screenshot-directory=~/Pictures/Screenshots

# supress logs
msg-level=ffmpeg=no
