# hardware decoding - AMD
hwdec=vaapi
hwdec-codecs=all

# native wayland output
vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
ao=pipewire

# scaling
correct-downscaling=yes
linear-downscaling=yes
scale=spline36
dscale=mitchell
cscale=bilinear

# HDR tone mapping
tone-mapping=spline
gamut-mapping-mode=perceptual
hdr-compute-peak=no
target-colorspace-hint=no

# cache for smoother local file playback
cache=yes
cache-pause=no
demuxer-max-bytes=400MiB
demuxer-max-back-bytes=100MiB
demuxer-readahead-secs=30

# subtitles
sub-auto=fuzzy
sub-font-size=36
sub-border-size=2.5

# screenshot format
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-directory=~/Pictures/Screenshots
screenshot-template="%F-%wH.%wM.%wS"

# misc
msg-level=ffmpeg=no
keep-open=yes
