{ config, pkgs, ... }:

let
  spicetify-nix = import (builtins.fetchTarball {
    url = "https://github.com/Gerg-L/spicetify-nix/archive/master.tar.gz";
  }) { };
  
  # nixpkgs-unstable, grab latest packages
  # without moving whole system off of 26.05 (stable release)
  # basically pick & choose packages to be the latest version
  pkgs-unstable = import (builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  }) {
    sytsem = pkgs.stdenv.hostPlatform.system;
    config.allowUnfree = true;
  };

  discord-scroll = pkgs.symlinkJoin {
    name = "discord-scroll";
    paths = [ (pkgs.discord.override { withVencord = true; }) ];
    buildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
      wrapProgram $out/bin/Discord \
      --add-flags "--enable-blink-features=MiddleClickAutoscroll"
    '';
  };
in

{
   # importing the hardware specific configuration generated by nixos-generate-config
   # this contains detected filesystems, UUIDs and kernel modules for this laptop.
   imports = [
     /etc/nixos/hardware-configuration.nix
     spicetify-nix.nixosModules.spicetify
   ]; 

   # system hostname
   networking.hostName = "nixos";

   # timezone, europe/london
   time.timeZone = "Europe/London";

   # using the latest kernel rather than LTS
   boot.kernelPackages = pkgs.linuxPackages_latest;

   # amd_pstate to active
   boot.kernelParams = [ 
     "amd_pstate=active"
     "mitigations=off"
   ];
   
   # zram optimisation
   boot.kernel.sysctl = {
    "vm.swappiness" = 180;
    "vm.vfs_cache_pressure" = 50;
   };
   
   # kills processes early if system runs out of memory
   systemd.oomd.enable = false;
   services.earlyoom.enable = true;

   # bootloader: systemd-boot, don't need GRUB since no dual boot and UEFI
   boot.loader.systemd-boot.enable = true;

   # allow systemd-boot to manage UEFI NVRAM boot entries directly
   boot.loader.efi.canTouchEfiVariables = true;

   boot.extraModprobeConfig = ''
    options ttm pages_limit=2097152
    options ttm page_pool_size=1048576
   '';
   
   # btrfs mount option overrides
   fileSystems."/".options = [ "compress=zstd:3" "noatime" ];
   fileSystems."/home".options = [ "compress=zstd:3" "noatime" ];
   fileSystems."/nix".options = [ "compress=zstd:3" "noatime" ];
   fileSystems."/var/log".options = [ "compress=zstd:3" "noatime" ];
   fileSystems."/boot".options = [ "umask=0077" ];
   fileSystems."/games" = {
  	device = "/dev/disk/by-uuid/9a47d749-9248-4be0-a850-b8adc9320d0b";
  	fsType = "btrfs";
  	options = [ "subvol=@games" "compress=zstd:3" "noatime" "exec" ];
   };
 
   # console keymapping
   console.keyMap = "us";

   # system locale
   i18n.defaultLocale = "en_GB.UTF-8";

   # users
   users.users.bradley = {
     isNormalUser = true;
     description = "Bradley";
     extraGroups = [ "wheel" "networkmanager" "seat" "video" "render" "input" ];
     shell = pkgs.zsh;
   };

   # logind behaviour
   services.logind.settings.Login = {
     HandleLidSwitch = "poweroff";
     HandleLidSwitchExternalPower = "suspend";
     HandleLidSwitchDocked = "ignore";
   };
   
   # lid handler service (note to track this to chezmoi)
   services.acpid.enable = true;
   services.acpid.lidEventCommands = ''
     /home/bradley/.local/bin/lid-handler.sh
   '';
   
   # USB headset stop sending VOLDOWN/UP
   services.udev.extraRules = ''
     SUBSYSTEM=="input", ATTRS{name}=="Kingston HyperX Cloud Stinger Wireless Consumer Control", ENV{LIBINPUT_IGNORE_DEVICE}="1"
   '';

   # set zsh system-wide as default shell
   programs.zsh = {
     enable = true;
     autosuggestions.enable = true;
     syntaxHighlighting.enable = true;
     enableCompletion = true;
     shellAliases = {
       ff = "fastfetch";
       ls = "eza --color=always";
       lt = "eza --tree --color=always";
       cat = "bat";
       nano = "nvim";
       grep = "rg";
       rebuild = "sudo nixos-rebuild switch";
       update = "sudo nixos-rebuild switch --upgrade";
       du = "dust";
       df = "duf";
       ps = "procs";
     };
   };

   # set kitty system-wide as default terminal
   environment.variables.TERMINAL = "kitty";
   
   # libexec
   environment.pathsToLink = [ "/libexec" ];

   # wayland native on every application
   environment.sessionVariables = {
     NIXOS_OZONE_WL = "1"; # electron based apps use wayland
     MOZ_ENABLE_WAYLAND = "1"; # firefox using wayland
     QT_QPA_PLATFORM = "wayland"; # any qt apps use wayland
     MESA_SHADER_CACHE_MAX_SIZE = "10G";
     SDL_VIDEODRIVER = "wayland"; 
     XDG_CURRENT_DESKTOP = "mango";
     XDG_SESSION_TYPE = "wayland";
     BROWSER = "firefox";
     GSETTINGS_SCHEMA_DIR = "${pkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${pkgs.gsettings-desktop-schemas.name}/glib-2.0/schemas";
   };

   # systemw-wide cursor theme
   environment.sessionVariables.XCURSOR_THEME = "Bibata-Modern-Classic";
   environment.sessionVariables.XCURSOR_SIZE = "30";
   
   # faster compilation
   nix.settings = {
     cores = 0; # 0 = auto-detect, use all available cores per build (like -j$(nproc) inside a single derivation's build script)
     max-jobs = "auto"; # how many derivations build in parallel simultaneously
     auto-optimise-store = true;
   };
  
   # automatic garbage collection
   nix.gc = {
     automatic = true;
     dates = "weekly";
     options = "--delete-older-than 30d";
   };

   # journald max usage
   services.journald.extraConfig = ''
     SystemMaxUse=200M
     RuntimeMaxUse=50M
   '';

   # enable steam
   programs.steam = {
     enable = true;
     extraCompatPackages = [ pkgs.proton-ge-bin ];
   }; 

   # gamemode
   programs.gamemode.settings = {
     general = {
       renice = 10;
     };

     gpu = {
       apply_gpu_optimisations = "accept-responsibility";
       gpu_device = 0;
       amd_performance_level = "high";
     };
   };

   # gamescope & gamemode
   programs.gamescope = {
      enable = true;
      package = pkgs-unstable.gamescope;
   };

   programs.gamemode.enable = true;

   # sched-ext scheduler set to lavd (more gaming/latency & desktop resposiveness targeted)
   services.scx = {
     enable = true;
     package = pkgs-unstable.scx.full;
     scheduler = "scx_lavd";
   };

   # trust waylock
   security.pam.services.waylock = { };

   # gnome-keyring PAM integration so it unlocks at login
   services.gnome.gnome-keyring.enable = true;

   # firmware update daemon
   services.fwupd.enable = true;
    
   # snapper: restore files in case of failure/backup
   services.snapper = {
     configs.root = {
     SUBVOLUME = "/";
     ALLOW_USERS = [ "bradley" ];
     TIMELINE_CREATE = true;
     TIMELINE_CLEANUP = true;
     TIMELINE_LIMIT_HOURLY = 5;
     TIMELINE_LIMIT_DAILY = 7;
     TIMELINE_LIMIT_WEEKLY = 4;
     };
   };

   # networkmanager to handle both ethernet/wifi (wireless)
   networking.networkmanager.enable = true;

   # firmware
   hardware.enableRedistributableFirmware = true;
   
   # dconf enable
   programs.dconf.enable = true;

   # AMD CPU microcode
   hardware.cpu.amd.updateMicrocode = true;
   
   # graphics: 32 bit for steam games & wine, added vulkan
   hardware.graphics = {
     enable = true;
     enable32Bit = true;
     extraPackages = [ pkgs-unstable.mangohud ];
     extraPackages32 = [ pkgs-unstable.pkgsi686Linux.mangohud ];
   };

   # enable for screen sharing, file pickers etc.
   xdg.portal.enable = true;
   xdg.portal.wlr.enable = true;
   xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
   xdg.portal.config = {
     common.default = "*";
     common."org.freedesktop.impl.portal.ScreenCast" = "wlr";
   };
 
   # audio: pipewire
   services.pulseaudio.enable = false;
   services.pipewire = {
     enable = true;
     alsa.enable = true;
     pulse.enable = true; # compatibility layer
   };
   security.rtkit.enable = true; # needed for pipewire for realtime scheduling

   # updating database for locate
   services.locate = {
     enable = true;
     package = pkgs.plocate;
     interval = "weekly";
   };

   # bluetooth (disabled right now)
   hardware.bluetooth.enable = false;

   # seatd needed to manage I/O
   services.seatd.enable = true;

   # zram compressed swap in RAM
   zramSwap.enable = true;

   # fstrim (ssd trimming)
   services.fstrim.enable = true;

   # tlp settings, disable power-profiles-daemon
   services.power-profiles-daemon.enable = false;
   services.tlp = {
     enable = true;
     settings = {
       CPU_SCALING_GOVERNOR_ON_AC = "performance";
       CPU_SCALING_GOVERNOR_ON_BAT = "powersave";

       CPU_ENERGY_PERF_POLICY_ON_AC = "performance";
       CPU_ENERGY_PERF_POLICY_ON_BAT = "balance_power";

       CPU_BOOST_ON_AC = 1;
       CPU_BOOST_ON_BAT = 0;

       SATA_LINKPWR_ON_AC = "med_power_with_dipm";

       AHCI_RUNTIME_PM_ON_AC = "on";
       AHCI_RUNTIME_PM_ON_BAT = "auto";

       RADEON_DPM_PERF_LEVEL_ON_AC = "auto";
       RADEON_DPM_PERF_LEVEL_ON_BAT = "low";

       AMDGPU_ABM_LEVEL_ON_AC = 0;
       AMDGPU_ABM_LEVEL_ON_BAT = 2;

       WIFI_PWR_ON_AC = "off";
       WIFI_PWR_ON_BAT = "on";

       WOL_DISABLE = "Y";

       USB_AUTOSUSPEND = 1;
     };
   };

   # needed services
   services.gvfs.enable = true;
   services.udisks2.enable = true;
   services.upower.enable = true;
   services.tumbler.enable = true;

   # polkit
   security.polkit.enable = true;

   # base system packages required
   environment.systemPackages = with pkgs; [
     pkgs-unstable.mangowc
     ((pkgs-unstable.waybar.override {
       cavaSupport = false;
       }).overrideAttrs (old: {
       	 doInstallCheck = false;
	 version = "unstable-2026-08-27";
	 src = pkgs.fetchFromGitHub {
	 owner = "Alexays";
	 repo = "Waybar";
	 rev = "6d60c8e02be67bb85bb9b1ea803f2fbcf0722002";
	 hash = "sha256-G6AcGuevhkYflQHhJq9GnLhEMgcI51Y6MYKBQvdRPDc=";
        };
       mesonFlags = old.mesonFlags ++ [ "-Dwwan=disabled" ];
     }))
     pkgs-unstable.kanshi
     pkgs-unstable.wlr-randr
     pkgs-unstable.mangohud
     tree-sitter
     baobab
     p7zip
     unrar
     xarchiver
     gammastep
     gnome-keyring
     linuxPackages.cpupower
     sysstat
     amdgpu_top
     ryzenadj
     delta
     dust
     duf
     libstrangle
     procs
     jq
     tokei
     chezmoi
     gcc
     gnumake
     fzf
     stylua
     shfmt
     shellcheck
     xdg-utils
     firefox
     neovim
     git
     curl
     wget
     pciutils
     usbutils
     file
     unzip
     zip
     btop
     tree
     ripgrep
     fd
     bat
     fastfetch
     kitty
     eza
     zinit
     starship
     xwayland
     bibata-cursors
     vulkan-loader
     vulkan-tools
     wl-clipboard
     grim
     slurp
     brightnessctl
     lm_sensors
     zoxide
     fuzzel
     thunar
     yazi
     waylock
     swayidle
     swaybg
     cliphist
     alsa-utils
     xdg-user-dirs 
     playerctl
     polkit_gnome
     ffmpegthumbnailer
     ntfs3g
     imv
     mpv
     gnome-themes-extra
     papirus-icon-theme
     nerd-fonts.departure-mono
     nwg-look
     easyeffects
     pavucontrol
     lazygit
     gh
     xlsclients
     vscode
     obsidian
     evtest
     glib
     gsettings-desktop-schemas
     motrix
     qbittorrent
     discord-scroll
     pulseaudio
   ];
   
   # direnv
   programs.direnv = {
     enable = true;
     nix-direnv.enable = true;
   };

   # xfconf
   programs.xfconf.enable = true;

   # thunar plugins
   programs.thunar.enable = true;
   programs.thunar.plugins = with pkgs; [
     thunar-volman
     thunar-archive-plugin
   ];

   # spicetify
   programs.spicetify = {
     enable = true;
     enabledExtensions = with spicetify-nix.packages.extensions; [
      # extensions here
     ];
     enabledCustomApps = with spicetify-nix.packages.apps; [
       marketplace
     ];
   };
   
   programs.spicetify.theme = {
     name = "blackout";
     src = pkgs.fetchFromGitHub {
       owner = "thefoodiee";
       repo = "blackout";
       rev = "main"; # will need to change hash if it gets updated
       hash = "sha256-/kB4cknOWeFE1mPZVQpmB2y/RGY/JjU61KXD+lWXDzg=";
     };
     injectCss = true;
     injectThemeJs = true;
     replaceColors = true;
     sidebarConfig = true;
     homeConfig = true;
   };   

   # default applications
   xdg.mime.defaultApplications = {
     "text/html" = "firefox.desktop";
     "x-scheme-handler/http" = "firefox.desktop";
     "x-scheme-handler/https" = "firefox.desktop";
     "x-scheme-handler/about" = "firefox.desktop";
     "x-scheme-handler/unknown" = "firefox.desktop";
     
     "image/png" = "imv.desktop";
     "image/jpeg" = "imv.desktop";
     "image/gif" = "imv.desktop";
     "image/webp" = "imv.desktop";
     "image/bmp" = "imv.desktop";
     "image/tiff" = "imv.desktop";

     "video/mp4" = "mpv.desktop";
     "video/x-matroska" = "mpv.desktop";
     "video/webm" = "mpv.desktop";
     "video/quicktime" = "mpv.desktop";
     "audio/mpeg" = "mpv.desktop";
     "audio/flac" = "mpv.desktop";
     "audio/ogg" = "mpv.desktop";

     "inode/directory" = "thunar.desktop";
   };

   # NixOS state version - shouldn't be changed and matches the release the system was first installed with (26.05.8477.062346a6d85b)
   system.stateVersion = "26.05";

   # allow installation of non-free packages
   nixpkgs.config.allowUnfree = true;

   # documentation: man pages and nix-os help tool
   documentation.man.enable = true;
   documentation.nixos.enable = true;

   # fonts available system-wide
   fonts.packages = with pkgs; [
     nerd-fonts.departure-mono
     nerd-fonts.jetbrains-mono
     noto-fonts
     noto-fonts-color-emoji
     noto-fonts-cjk-sans
     liberation_ttf
     dejavu_fonts
   ];
   
   # fonts system-wide
   fonts.fontconfig.defaultFonts = {
       serif = [ "DepartureMono Nerd Font Propo" ];
       sansSerif = [ "DepartureMono Nerd Font Propo" ];
       monospace = [ "DepartureMono Nerd Font Mono" ];
   };
}
