server:
    interface: 127.0.0.1
    port: 53
    access-control: 127.0.0.0/8 allow
    do-ip4: yes
    do-ip6: yes
    do-udp: yes
    do-tcp: yes
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
    cache-min-ttl: 300
    cache-max-ttl: 86400
    prefetch: yes
    msg-cache-size: 64m
    rrset-cache-size: 128m
    hide-identity: yes
    hide-version: yes
    qname-minimisation: yes
    private-domain: "home"
    domain-insecure: "home"

forward-zone:
    name: "home"
    forward-addr: 192.168.0.1

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
    forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
    forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com
