{ config, pkgs, nixpkgs-unstable, spicetify-nix, ... }:

{
   # importing the hardware specific configuration generated by nixos-generate-config
   # this contains detected filesystems, UUIDs and kernel modules for this laptop.
   imports = [
     ./hardware-configuration.nix
     ./modules/hardware.nix
     ./modules/system.nix
     ./modules/desktop.nix
     ./modules/gaming.nix
     ./modules/services.nix
     ./modules/programs.nix
   ]; 

   # NixOS state version - shouldn't be changed and matches the release the system was first installed with (26.05.8477.062346a6d85b)
   system.stateVersion = "26.05";

   # allow installation of non-free packages
   nixpkgs.config.allowUnfree = true;
}
