# More option see https://github.com/DreamMaoMao/mango/wiki/

# autostarts
exec-once=/home/bradley/.config/mango/autostart.sh

# effects
source=~/.config/mango/conf.d/effects.conf

# layout
source=~/.config/mango/conf.d/layout.conf

# inputs
source=~/.config/mango/conf.d/input.conf

# keybinds
source=~/.config/mango/conf.d/binds.conf

# rules
source=~/.config/mango/conf.d/rules.conf

# miscellaneous
source=~/.config/mango/conf.d/misc.conf
