# keyboard
repeat_rate=65
repeat_delay=225
numlockon=0
xkb_rules_layout=us

# Trackpad
# need relogin to make it apply
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
trackpad_disable_while_typing=1
trackpad_left_handed=0
trackpad_middle_button_emulation=1
trackpad_scroll_factor=0.5
swipe_min_threshold=1

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0

# per-device overrides
# disable controller pad mouse movement
devicerule=name:1356:3302:Sony_Interactive_Entertainment_DualSense_Wireless_Controller_Touchpad,send_events_mode:1
