# layer rule
layerrule=animation_type_open:zoom,layer_name:fuzzel
layerrule=animation_type_close:zoom,layer_name:fuzzel

# monitor rules for external & internal monitors
monitorrule=name:eDP-1,width:1920,height:1080,refresh:60,x:2560,y:0,scale:1,rr:0,vrr:0
monitorrule=name:HDMI-A-1,width:2560,height:1440,refresh:144,x:0,y:0,scale:1,rr:0,vrr:0

# floating rules
windowrule=isfloating:1,appid:xdg-desktop-portal-gtk
windowrule=isfloating:1,appid:md.Obsidian,title:Settings
windowrule=isfloating:1,appid:firefox,title:Library
windowrule=isfloating:1,appid:org.pulseaudio.pavucontrol
windowrule=isfloating:1,appid:thunar
windowrule=isfloating:1,appid:mpv
windowrule=isfloating:1,appid:imv
windowrule=isfloating:1,appid:steam,title:Steam Settings
windowrule=isfloating:1,appid:xarchiver
