# layer rule
layerrule=animation_type_open:zoom,layer_name:fuzzel
layerrule=animation_type_close:zoom,layer_name:fuzzel

# floating rules
windowrule=isfloating:1,appid:xdg-desktop-portal-gtk
windowrule=isfloating:1,appid:md.Obsidian,title:Settings
windowrule=isfloating:1,appid:firefox,title:Library
windowrule=isfloating:1,appid:org.pulseaudio.pavucontrol
windowrule=isfloating:1,appid:thunar
windowrule=isfloating:1,appid:mpv
windowrule=isfloating:1,appid:imv
windowrule=isfloating:1,appid:steam,title:Steam Settings
windowrule=isfloating:1,appid:xarchiver

# idle-inhibit rules
windowrule=idleinhibit_when_focus:1,appid:firefox
windowrule=idleinhibit_when_focus:1,appid:mpv
windowrule=idleinhibit_when_focus:1,appid:steam_app_.*
windowrule=idleinhibit_when_focus:1,title:(?i)(hollow knight|silksong)
